### ISSUE TITLE
Publish versions that just include a single benchmark

### ISSUE THREAD

**Issue by parttimenerd** [renaissance-benchmarks/renaissance#376] opened 2023-03-22 08:02 UTC
Many applications of the benchmark only need a few of the benchmarks. Would it be possible to offer a JAR for every one of these benchmarks (e.g. `renaissance-dotty.jar`)?

I'm happy to help implement this.

**Comment by ceresek** [comment] 2023-03-22 08:22
The main harness can currently self-extract the classes required to run a single benchmark, see  #341. Is this what you have in mind, or is there some feature missing ?

**Comment by parttimenerd** [comment] 2023-03-22 08:38
No, my use case is using it an OpenJDK test case. I currently download the whole renaissance benchmark, but this leads to really long test runs when I actually just use one or two benchmarks. Being able to download them separately would really help.

The test case are related to profiling APIs and renaissance benchmarks are great to find bugs.

**Comment by lbulej** [comment] 2023-03-23 10:45
Well, the simplest solution to the problem is just taking the fat jar, unpack it, and create archives (with all dependencies) for separate benchmarks and including just a subset of the `benchmarks.properties` and `modules.properties` files. This could be implemented as a post-processing script. 

Making this part of the build system would probably require some SBT magic, but it could be unwieldy, because the build system is currently structured around benchmark groups with common dependencies, so it does not really have a (strong) notion of individual benchmark projects.

Even in the post processing script you would have to decide whether you really want individual benchmarks, or benchmark groups. Because, e.g., if you wanted to split individual Spark benchmarks, you would have to package 200MB of dependencies for each benchmark.

While I think that ideally we should build the benchmarks, the API + core classes and the harness as separate artifacts (available through Maven central) and the bundling step would be extra, it would require a significant overhaul of the build process which I would like to avoid at the moment.

The post-processing script could be a simpler solution. We could keep it in the repository (it would not be the first) and use it to prepare releases.

**Comment by parttimenerd** [comment] 2023-04-24 16:23
> The post-processing script could be a simpler solution. We could keep it in the repository (it would not be the first) and use it to prepare releases.

Can I help with this?

**Comment by farquet** [comment] 2023-05-04 09:41
Closing as it seems that the agreed solution doesn't require changes on the renaissance side.

**Closed by farquet** 2023-05-04 09:41 UTC
