### ISSUE TITLE
finagle-chirper reports exceptions during execution on Zing VM

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#345] opened 2022-01-26 10:05 UTC
While executing (like, once every 10ish repetitions), finagle-chirper reports exceptions when running on Zing VM:

```
====== finagle-chirper (web) [default], iteration 43 started ======                                                                                                                       [53/1878]
Resetting master, feed map size: 5000                                                                                                                                                              
GC before operation: completed in 94.977 ms, heap usage 3.402 GB -> 592.000 MB.                                                                                                                    
[2022-01-26T09:52:51.475+0000] com.twitter.finagle.util.DefaultMonitor (com.twitter.finagle.util.DefaultMonitor logWithRemoteInfo)                                                                 
WARNING: Exception propagated to the default monitor (upstream address: /127.0.0.1:48902, downstream address: n/a, label: ).                                                                       
                                                                                                 
java.util.ConcurrentModificationException: mutation occurred during iteration
        at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
        at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)       
        at org.renaissance.twitter.finagle.FinagleChirper$Master.analyze(FinagleChirper.scala:58) 
        at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$hashStartCountInAllFeeds$1(FinagleChirper.scala:84)
        at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$hashStartCountInAllFeeds$1$adapted(FinagleChirper.scala:77)
        at scala.collection.immutable.List.foreach(List.scala:333) 
        at org.renaissance.twitter.finagle.FinagleChirper$Master.hashStartCountInAllFeeds(FinagleChirper.scala:77)
        at org.renaissance.twitter.finagle.FinagleChirper$Master.$anonfun$apply$9(FinagleChirper.scala:184)
        at com.twitter.util.Try$.apply(Try.scala:26)             
        at com.twitter.util.ExecutorServiceFuturePool$$anon$4.run(FuturePool.scala:163)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:887)       
WARNING: This benchmark provides no result that can be validated.
There is no way to check that no silent failure occurred.                          
====== finagle-chirper (web) [default], iteration 43 completed (3481.243 ms) ======
```

```shell
java version "11.0.13" 2021-12-15 LTS
Java Runtime Environment Zing21.12.0.0+2 (build 11.0.13+8-LTS)
Zing 64-Bit Tiered VM Zing21.12.0.0+2 (build 11.0.13-zing_21.12.0.0-b3-product-linux-X86_64, mixed mode)
```

Observed with dc88e0b5d814a705edecd1ad0992281602b4c4c3.

**Comment by farquet** [comment] 2022-04-04 07:58
Closing since this is a duplicate of #354.

**Closed by farquet** 2022-04-04 07:58 UTC
Labels: bug, duplicate, compatibility
