### ISSUE TITLE
Transient NullPointerException and deadlock in the reactors benchmark

### ISSUE THREAD

**Issue by gergo-** [renaissance-benchmarks/renaissance#359] opened 2022-04-14 15:42 UTC
At Oracle Labs we have been seeing the reactors benchmark sometimes throw a `NullPointerException` and then deadlock. Here's a stack trace from a recent example:
```
...
====== reactors (concurrency) [default], iteration 8 completed (21244.608 ms) ======
====== reactors (concurrency) [default], iteration 9 started ======
GC before operation: completed in 18.915 ms, heap usage 755.170 MB -> 30.994 MB.
Baseline workload: Reactor scheduling events
BigBench workload: Many-to-many message ping pong
CountingActor workload: Single reactor event processing
Fibonacci workload: Dynamic reactor mix with varying lifetimes
ForkJoinCreation workload: Reactor creation performance
ForkJoinThroughput workload: Reactor processing performance
PingPong workload: Reactor pair sequential ping pong performance
StreamingPingPong workload: Reactor pair overlapping ping pong performance
java.lang.NullPointerException: Cannot invoke "io.reactors.Channel$LowPriority.send(Object)" because "$this" is null
	at io.reactors.package$LowPriorityChannelOps$.$bang$extension(package.scala:171)
	at org.renaissance.actors.StreamingPingPong$PingPongInner$2.$anonfun$ping$7(Reactors.scala:462)
	at org.renaissance.actors.StreamingPingPong$PingPongInner$2.$anonfun$ping$7$adapted(Reactors.scala:461)
	at io.reactors.Events$OnEventOrDone.react(Events.scala:1665)
	at io.reactors.Events$Push.reactAll(Events.scala:1275)
	at io.reactors.Events$Push.reactAll$(Events.scala:1267)
	at io.reactors.Events$Emitter.reactAll(Events.scala:1489)
	at io.reactors.Events$Emitter.react(Events.scala:1494)
	at io.reactors.EventQueue$UnrolledRing.dequeue(EventQueue.scala:116)
	at io.reactors.Connector.dequeue(Connector.scala:61)
	at io.reactors.concurrent.Frame.drain$1(Frame.scala:322)
	at io.reactors.concurrent.Frame.processEvents(Frame.scala:345)
	at io.reactors.concurrent.Frame.processBatch(Frame.scala:494)
	at io.reactors.concurrent.Frame.isolateAndProcessBatch(Frame.scala:210)
	at io.reactors.concurrent.Frame.executeBatch(Frame.scala:183)
	at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.executeNow(JvmScheduler.scala:126)
	at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.postschedule(JvmScheduler.scala:151)
	at io.reactors.JvmScheduler$Executed.postschedule(JvmScheduler.scala:273)
	at io.reactors.concurrent.Frame.executeBatch(Frame.scala:202)
	at io.reactors.JvmScheduler$Executed$$anon$5.run(JvmScheduler.scala:255)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
As soon as this error is encountered, the benchmark hangs forever with 0% CPU usage and must be killed explicitly.

The stack traces from different Renaissance versions differ in line numbers, but the problem is always a `NullPointerException` in the inner one of the two nested lambdas in `PingPongInner`; sometimes in the PingPong workload, sometimes in StreamingPingPong.
I can reproduce this most readily on Linux on an AArch64 machine, although we have seen [one report](https://github.com/oracle/graal/issues/4297) from a user on Windows/AMD64. On our internal Linux/AArch64 systems I typically get this failure at least once out of 10 runs of the benchmark. It occurs at various times, often as early as iteration 1 or 2 (but not 0, as far as I have seen), but sometimes on later iterations. We haven't seen it occur on Linux/AMD64 during normal runs of the benchmark, only when running it in particular GraalVM-specific configurations (extra agents, native images).

But importantly, I believe this bug is *not* specific to GraalVM, as I have observed it on other JDKs as well. Overall I have seen the failure on most combinations of Renaissance versions {0.11, 0.13, 0.14} x JDK versions {11, 17} x JDK distributions {OpenJDK, Oracle JDK, Oracle LabsJDK, GraalVM}.

Please let me know what other information I can provide to help debug this.

**Comment by farquet** [comment] 2022-05-17 16:36
Good find @lbulej ! It sounds plausible that this would fix the problem. But since it's a very transient problem, I don't think we can be 100% confident that this is the final fix even with intensive local testing of this candidate.

What I would suggest is to release a renaissance 0.14.1 including this change, which is anyway desirable because of the fix for #354 which landed on master.

The GraalVM team would be happy to default its testing to 0.14.1 and report back. Since the current transient issue happens only a couple of times a month (despite our very intensive benchmarking), we could see if those errors stop appearing.

Thoughts?

**Comment by lbulej** [comment] 2022-05-17 17:06
I was thinking that if @gergo- can, unlike me, "reproduce this most readily on Linux on an AArch64 machine", he could give the provided jar a quick try on said AArch64 machine to see if it can help (everything should be strictly sequential until the point we fire off the first message to a channel, but by that time, everything should be properly initialized).

I have few other things I would like to clean up in the `reactors` benchmark &mdash; there are two other sub-benchmarks with initialization I don't like (probably harmless, but also starting communication either from a constructor or the reactor initializer) and we should use a timeout when waiting on the futures to avoid benchmark lockups in cases like this (but it's not strictly necessary if we can get rid of the bug).

**So let's give it a day or two and if I don't hear from @gergo- , I'll pack up the changes and release 0.14.1, because these changes should not hurt &mdash; on the contrary.**

Also, after the reorganization, it became apparent that the reactor code of `PingPong` and `StreamingPingPong` is basically identical, the only difference being the window size (the number of initial triggers sent to one of the channels), so we might discuss whether we want to do something about it. But that's for another time.

**Comment by gergo-** [comment] 2022-05-20 08:00
I've done some testing of the new build, and the NPE and deadlock seem to be gone. A formal release would be much appreciated. Thank you!

**Comment by lbulej** [comment] 2022-05-20 08:48
Thank you for testing! I'll pack it up and do a release soon.

**Closed** 2022-05-22 19:01 UTC
Labels: bug
